language: R
sudo: false
cache: packages

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      - libsodium-dev
      - libbcurl4-openssl-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
